FROM alpine:3.14

RUN apk add --no-cache git openssh bash && \
    ssh-keygen -A && \
    adduser git -D -G root -h /home/git -s /bin/bash && \
    passwd -d git && \
    su git -c "mkdir /home/git/.ssh && \
    ssh-keygen -t ed25519 -f /home/git/.ssh/id_ed25519 -P '' && \
    mv /home/git/.ssh/id_ed25519.pub /home/git/.ssh/authorized_keys && \
    mkdir /home/git/test.git && \
    git --bare init /home/git/test.git"

VOLUME ["/home/git/.ssh", "/home/git/test.git/hooks"]
WORKDIR /home/git

CMD ["/usr/sbin/sshd", "-D", "-f", "/etc/ssh/sshd_config"]

